# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O03mMtZIA0zbaGvX_XN-mwAqueQfIjYZ
"""

import streamlit as st
import pandas as pd
import seaborn as sns
import warnings
import matplotlib.pyplot as plt

st.title("Wage prediction")

st.write("Прогнозирование заработной платы на основе предикторов как возраст, пол, региона и других факторов")

# Игнорировать предупреждения
warnings.filterwarnings('ignore')

data1 = pd.read_excel('/content/drive/MyDrive/2-T_2022_v1.xlsx')
data2 = pd.read_excel('/content/drive/MyDrive/2-T_2022_v2.xlsx')

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

wage_df = pd.concat([df1, df2], ignore_index=True)

# Создаем столбец Age
wage_df['Age'] = 2024 - wage_df['SPPN1']

# Отрисовка гистограммы для столбца 'Age'
st.write("Гистограмма возраста")
fig1, ax1 = plt.subplots()
sns.histplot(wage_df['Age'], ax=ax1)

st.pyplot(fig1)

# Отрисовка гистограммы для столбца 'SPPN1'
st.write("Гистограмма SPPN1")
fig2, ax2 = plt.subplots()
sns.histplot(wage_df['SPPN1'], ax=ax2)
st.pyplot(fig2)

selected_columns = ['SUO', 'SPPN1', 'SP', 'OKED1', 'KFS', 'KOPF', 'KSE', 'KRP', 'KATO1', 'VAL_NUM']
correlation_matrix = wage_df[selected_columns].corr()

correlation_matrix

st.write("Корреляционная матрица:")
st.write(correlation_matrix)