# -*- coding: utf-8 -*-
"""strimlit_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E96EdOKpC3Bke_bLaEsOynMr5Hs7PyF6
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np

st.title("Wage prediction")

st.write("Прогнозирование заработной платы на основе предикторов как возраст, пол, региона и других факторов")

import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
data1 = pd.read_excel('/content/drive/MyDrive/2-T_2022_v1.xlsx')
data2 = pd.read_excel('/content/drive/MyDrive/2-T_2022_v2.xlsx')

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

wage_df = pd.concat([df1, df2], ignore_index=True)

st.write(wage_df)

wage_df_info = wage_df.loc[wage_df['KCP'] == 252101]

df_num = wage_df_info.select_dtypes(exclude='object')

sns.histplot(df_num['SPPN1'])
st.pyplot()

df_num['Age'] = 2024 - df_num['SPPN1']
sns.histplot(df_num['Age'])
st.pyplot()

df_num['KATO'] = df_num['KATO1'].astype(str).str[:2]
df_num['KATO'] = df_num['KATO'].replace('na', np.nan)
df_num['KATO'] = df_num['KATO'].astype(float)

# Вывод матрицы корреляции
st.write(df_num[['SUO', 'SPPN1', 'SP', 'OKED1', 'KFS', 'KOPF', 'KSE', 'KRP', 'KATO', 'VAL_NUM']].corr())